#!/usr/bin/env python3
"""
Game2 #19 데모 패키지 생성
"""
import os, shutil, json
from datetime import datetime

DEMO_DIR = "/workspace/demo_game2_19"
os.makedirs(DEMO_DIR, exist_ok=True)

# 1. 하이라이트 클립 복사
shutil.copy(
    "/workspace/game_results/game2/highlight_game2_19.mp4",
    f"{DEMO_DIR}/highlight_#19_game2.mp4"
)

# 2. 저지맵 복사 (개인 + 합성)
shutil.copy(
    "/workspace/game_results/game2/jerseymap_game2_19.png",
    f"{DEMO_DIR}/heatmap_#19_game2.png"
)
shutil.copy(
    "/workspace/game_results/game2/jerseymap_game2_combined_19_40_89.png",
    f"{DEMO_DIR}/heatmap_top3_comparison_game2.png"
)

# 3. 출전 구간 요약 리포트 생성
report = """\
=====================================
  IceIQ PLAYER REPORT — DEMO
  Player #19 | Game 2
  Generated: {date}
=====================================

[ VIDEO ]
  Source   : HockeyTV YouTube Channel
  Title    : 블루웨일즈 GAME LESSON [FULLGAME] 2026.03.31
  Duration : ~52 min

[ PLAYER TRACKING SUMMARY ]
  Jersey Number : #19
  Team          : AWAY
  Detection     : 125 frames matched
  Confusion Blocked : 2 false positives eliminated

[ TIME ON ICE ]
  Total Shifts  : 11
  Total Ice Time : 4 min 36 sec

  Shift Breakdown:
  ┌────┬─────────────────────┬──────────┐
  │ #  │ Time                │ Duration │
  ├────┼─────────────────────┼──────────┤
  │ 01 │ 13:07 → 13:41       │  34 sec  │
  │ 02 │ 16:07 → 16:24       │  18 sec  │
  │ 03 │ 17:03 → 17:20       │  17 sec  │
  │ 04 │ 26:13 → 26:51       │  38 sec  │
  │ 05 │ 30:46 → 30:54       │   8 sec  │
  │ 06 │ 33:19 → 33:40       │  21 sec  │
  │ 07 │ 35:40 → 36:07       │  27 sec  │
  │ 08 │ 51:58 → 52:06       │   8 sec  │
  │ 09 │ 53:31 → 53:57       │  26 sec  │
  │ 10 │ 55:44 → 56:23       │  39 sec  │
  │ 11 │ 62:41 → 63:22       │  41 sec  │
  └────┴─────────────────────┴──────────┘

[ POSITION ANALYSIS ]
  Estimated Position : Forward / All-around Player
  Primary Zone       : Center ice & left-side half-space
  Activity Pattern   :
    - High activity across center circle area
    - Covers wide range of ice surface
    - Visible in both offensive and defensive zones
    - Consistent shift pattern throughout the game

[ HEATMAP FILES ]
  heatmap_#19_game2.png        — Individual positioning map
  heatmap_top3_comparison_game2.png — Comparison vs TOP3 players

[ HIGHLIGHT CLIP ]
  highlight_#19_game2.mp4      — All 11 shifts (4 min 36 sec)

-------------------------------------
  Generated by IceIQ — AI Hockey Analysis
  github.com/gret24/iceiq
=====================================
""".format(date=datetime.now().strftime("%Y-%m-%d %H:%M"))

with open(f"{DEMO_DIR}/player_report_#19.txt", "w") as f:
    f.write(report)

# 4. README
readme = """\
# IceIQ Demo Package — Player #19

## Contents
| File | Description |
|------|-------------|
| `highlight_#19_game2.mp4` | Highlight clips — all 11 shifts (4m 36s) |
| `heatmap_#19_game2.png` | Individual position heatmap |
| `heatmap_top3_comparison_game2.png` | TOP3 player zone comparison |
| `player_report_#19.txt` | Full player report with shift breakdown |

## About IceIQ
AI-powered hockey player tracking system.
- Automatic jersey number recognition (EasyOCR + YOLOv8)
- Multi-feature player identification
- Position heatmap visualization
- Highlight clip extraction

**github.com/gret24/iceiq**
"""

with open(f"{DEMO_DIR}/README.md", "w") as f:
    f.write(readme)

print("데모 패키지 생성 완료!")
import subprocess
result = subprocess.run(["ls", "-lh", DEMO_DIR], capture_output=True, text=True)
print(result.stdout)
